""" Define a dictionary containing the units for the available variables """

units = {"event_id": '',
         "timestamp": 'seconds',
         "temp_inside": 'degrees Celcius',
         "temp_outside": 'degrees Celcius',
         "humidity_inside": '%',
         "humidity_outside": '%',
         "barometer": 'hectoPascal',
         "wind_dir": 'degrees',
         "wind_speed": 'm/s',
         "solar_rad": 'Watt/square metre',
         "uv": '',
         "evapotranspiration": 'millimetre',
         "rain_rate": 'millimetre/hour',
         "heat_index": 'degrees Celcius',
         "dew_point": 'degrees Celcius',
         "wind_chill": 'degrees Celcius',
         "nanoseconds": 'nanoseconds',
         "ext_timestamp": 'nanoseconds',
         "data_reduction": '',
         "trigger_pattern": '',
         "baseline": 'ADC counts',
         "std_dev": 'ADC counts',
         "n_peaks": '',
         "pulseheights": 'ADC counts',
         "integrals": 'ADC counts nanonseconds',
         "traces": '',
         "event_rate": 'Hertz'}
